Disable the RSS check

diff --git a/.github/workflows/native-build-development.yml b/.github/workflows/native-build-development.yml
--- a/.github/workflows/native-build-development.yml
+++ b/.github/workflows/native-build-development.yml
@@ -48,42 +48,42 @@ jobs:
             -Dquarkus.native.container-build=true \
             -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-native-image:20.1.0-java11
 
-      - name: Check RSS
-        env:
-          QUICKSTART_VERSION: "1.0-SNAPSHOT"
-          RSS_THRESHOLD: "40000"
-          START_TIME_THRESHOLD: "1000"
-          REMOTE_OBJECT_NAME: "pmap.out"
-          BUCKET_NAME: ${{ secrets.IBM_COS_BUCKET_NAME }}
-          API_KEY: ${{ secrets.IBM_COS_SERVICE_CREDENTIAL_API_KEY }}
-          SERVICE_INSTANCE_ID: ${{ secrets.IBM_COS_SERVICE_CREDENTIAL_RESOURCE_INSTANCE_ID }}
-
-        run: |
-          sudo apt-get update -o Dir::Etc::sourcelist="sources.list" -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"
-          sudo apt-get install -y gnupg2 gnupg-agent
-          echo Installing SDKMAN
-          curl -s "https://get.sdkman.io" | bash
-          source ~/.sdkman/bin/sdkman-init.sh
-          sdk install jbang
-          getting-started/target/getting-started-${QUICKSTART_VERSION}-runner -Xmx2m -Dquarkus.http.io-threads=1 -Dquarkus.vertx.worker-pool-size=1 > server.log &
-          sleep 2
-          appPid=$!
-          pmap -x $appPid > pmap.out
-          ps --no-headers  -C getting-started-${QUICKSTART_VERSION}-runner -o rss > rss.out
-          rss=$(< rss.out)
-          echo "Max RSS Threshold (kB): ${RSS_THRESHOLD}"
-          echo "RSS (kB): $rss"
-          startTime=$(grep -oP "started in \K([0-9]*\.[0-9]*)" server.log)
-          startTimeMs=$(echo "$startTime*1000/1" | bc)
-          echo "Start time Threshold (ms): ${START_TIME_THRESHOLD}"
-          echo "Start time (ms): $startTimeMs"
-          jbang .github/RssRegression.java ${BUCKET_NAME} ${API_KEY} ${SERVICE_INSTANCE_ID} ${REMOTE_OBJECT_NAME} pmap.old.out pmap.out
-          [ "$rss" -lt "${RSS_THRESHOLD}" ] && [ "$startTimeMs" -lt "${START_TIME_THRESHOLD}" ] && exit 0 || exit 1
-
-      - uses: actions/upload-artifact@v1
-        with:
-          name: pmap
-          path: pmap.out
+      #- name: Check RSS
+      #  env:
+      #    QUICKSTART_VERSION: "1.0-SNAPSHOT"
+      #    RSS_THRESHOLD: "40000"
+      #    START_TIME_THRESHOLD: "1000"
+      #    REMOTE_OBJECT_NAME: "pmap.out"
+      #    BUCKET_NAME: ${{ secrets.IBM_COS_BUCKET_NAME }}
+      #    API_KEY: ${{ secrets.IBM_COS_SERVICE_CREDENTIAL_API_KEY }}
+      #    SERVICE_INSTANCE_ID: ${{ secrets.IBM_COS_SERVICE_CREDENTIAL_RESOURCE_INSTANCE_ID }}
+      #
+      #  run: |
+      #    sudo apt-get update -o Dir::Etc::sourcelist="sources.list" -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"
+      #    sudo apt-get install -y gnupg2 gnupg-agent
+      #    echo Installing SDKMAN
+      #    curl -s "https://get.sdkman.io" | bash
+      #    source ~/.sdkman/bin/sdkman-init.sh
+      #    sdk install jbang
+      #    getting-started/target/getting-started-${QUICKSTART_VERSION}-runner -Xmx2m -Dquarkus.http.io-threads=1 -Dquarkus.vertx.worker-pool-size=1 > server.log &
+      #    sleep 2
+      #    appPid=$!
+      #    pmap -x $appPid > pmap.out
+      #    ps --no-headers  -C getting-started-${QUICKSTART_VERSION}-runner -o rss > rss.out
+      #    rss=$(< rss.out)
+      #    echo "Max RSS Threshold (kB): ${RSS_THRESHOLD}"
+      #    echo "RSS (kB): $rss"
+      #    startTime=$(grep -oP "started in \K([0-9]*\.[0-9]*)" server.log)
+      #    startTimeMs=$(echo "$startTime*1000/1" | bc)
+      #    echo "Start time Threshold (ms): ${START_TIME_THRESHOLD}"
+      #    echo "Start time (ms): $startTimeMs"
+      #    jbang .github/RssRegression.java ${BUCKET_NAME} ${API_KEY} ${SERVICE_INSTANCE_ID} ${REMOTE_OBJECT_NAME} pmap.old.out pmap.out
+      #    [ "$rss" -lt "${RSS_THRESHOLD}" ] && [ "$startTimeMs" -lt "${START_TIME_THRESHOLD}" ] && exit 0 || exit 1
+      #
+      #- uses: actions/upload-artifact@v1
+      #  with:
+      #    name: pmap
+      #    path: pmap.out
 
       - name: Delete Local Artifacts From Cache
         shell: bash
